/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pr0Fav;

import java.io.File;

public class Main {

    public static void main(String[] args) {
        Window window = new Window();
    }
}
